# Permalinks
#
permalink:           pretty

markdown:            kramdown

# About/contact
author:
  name:              Nachikethas
  twitter:           https://twitter.com/ajnachikethas
  linkedin:          https://www.linkedin.com/in/nachikethasaj
  github:            https://github.com/nachikethas
  scholar:           https://scholar.google.com/citations?user=ls-7rRMAAAAJ
  email:             nanantha [at] usc.edu

urls:
    usc:             http://www.usc.edu/
    uscee:           http://ee.usc.edu/
    bhaskar:         http://ceng.usc.edu/~bkrishna/

# Setup
title:               Nachikethas A. Jagadeesan
tagline:             ''
description:         ''

url:                 http://localhost:4000
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

gems: [jekyll-paginate]

sass:
    sass_dir: _sass
    style: :compressed
