# Permalinks
#
permalink:           pretty

markdown:            kramdown

# About/contact
author:
  name:              Nachikethas
  twitter:           https://twitter.com/ajnachikethas
  linkedin:          https://www.linkedin.com/in/nachikethasaj
  github:            https://github.com/nachikethas
  scholar:           https://scholar.google.com/citations?user=ls-7rRMAAAAJ
  email:             nanantha [at] usc.edu

urls:
    usc:             http://www.usc.edu/
    uscee:           http://ee.usc.edu/
    bhaskar:         http://ceng.usc.edu/~bkrishna/

# Setup
title:               Nachikethas A. Jagadeesan
#tagline:             ''
#description:         ''

#url:                 http://www.nachikethas.com
#baseurl:             ''
paginate:            3
paginate_path:       "page:num"
excerpt_separator:   <!--more-->

# Sidebar Links
slinks:
    - title: <i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Home
      url: /
    - title: <i class="fa fa-user-circle fa-fw" aria-hidden="true"></i>&nbsp; About
      url: /about/
    - title: <i class="fa fa-tags fa-fw" aria-hidden="true"></i>&nbsp; Tags
      url: /tags/

gems: [jekyll-paginate]

sass:
    sass_dir: _sass
    style: :compressed

# Google Analytics
ga:                  UA-86479860-1
